# Generated by Django 4.2 on 2023-04-12 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("decisions", "0003_decision"),
    ]

    operations = [
        migrations.CreateModel(
            name="RevisionComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("type", models.SmallIntegerField(default=0)),
                ("content", models.CharField(max_length=2048)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("version", models.SmallIntegerField(blank=True, null=True)),
                ("decision", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="decisions.decision")),
                (
                    "user",
                    models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "verbose_name": "Revision/Comment Record",
                "ordering": ["-date_created"],
            },
        ),
    ]
