---
version: "3.4"
services:
  adr-dj-db:
    image: "postgres:14-alpine"
    container_name: "adr-dj-db"
    hostname: "adr-dj-db"
    env_file:
      - "dev.env"
      - "creds.env"
    ports:
      - "5432:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
  adr-dj-ad:
    image: "ghcr.io/psmware-ltd/active-directory-it:develop"
    container_name: "adr-dj-ad"
    hostname: "adr-dj-ad"
    env_file:
      - "dev.env"
      - "creds.env"
    volumes:
      - "./users.ldif:/ldap/users.ldif"

volumes:
  postgres_data: {}
